version: '3.8'

services:
  # Django Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_static:/app/staticfiles
      - backend_media:/app/media
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/plockly
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  # React Frontend
  frontend:
    build: ./frontend
    ports:
      - "3001:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0 --port 5173

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=plockly
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  postgres_data:
  backend_static:
  backend_media:
